apiVersion: apps/v1
kind: Dep
metadata:
  labels:
    app: nginx-github
  name: nginx-github
  env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-github
  template:
    metadata:
      labels:
        app: nginx-github
    spec:
      containers:
      - image: nginx
        name: nginx
